### ISSUE TITLE
Position problem

### ISSUE THREAD

**Issue by drclong** [DavidFW1960/bom-weather-card#3]
Hi David,
Thanks for your awesome work! However I am having a small issue getting the appearance correct.
Can you point me in the right dirction to get the text up the top in the right place?
Kind regards,
Chris,
![image](https://user-images.githubusercontent.com/19884789/75091977-42746a80-55c7-11ea-80e9-211c2590dffe.png)
`````
cards:
  - entity_apparent_temp: sensor.bom_bairnsdale_feels_like_c
    entity_current_conditions: sensor.bom_bairnsdale_icon_0
    entity_current_text: sensor.bom_current_text
    entity_daily_summary: sensor.bom_bairnsdale_detailed_summary_0
    entity_daytime_high: sensor.bom_today_max
    entity_forecast_high_temp_1: sensor.bom_bairnsdale_max_temp_c_1
    entity_forecast_high_temp_2: sensor.bom_bairnsdale_max_temp_c_2
    entity_forecast_high_temp_3: sensor.bom_bairnsdale_max_temp_c_3
    entity_forecast_high_temp_4: sensor.bom_bairnsdale_max_temp_c_4
    entity_forecast_high_temp_5: sensor.bom_bairnsdale_max_temp_c_5
    entity_forecast_icon_1: sensor.bom_bairnsdale_icon_1
    entity_forecast_icon_2: sensor.bom_bairnsdale_icon_2
    entity_forecast_icon_3: sensor.bom_bairnsdale_icon_3
    entity_forecast_icon_4: sensor.bom_bairnsdale_icon_4
    entity_forecast_icon_5: sensor.bom_bairnsdale_icon_5
    entity_forecast_low_temp_1: sensor.bom_bairnsdale_min_temp_c_1
    entity_forecast_low_temp_2: sensor.bom_bairnsdale_min_temp_c_2
    entity_forecast_low_temp_3: sensor.bom_bairnsdale_min_temp_c_3
    entity_forecast_low_temp_4: sensor.bom_bairnsdale_min_temp_c_4
    entity_forecast_low_temp_5: sensor.bom_bairnsdale_min_temp_c_5
    entity_humidity: sensor.bom_bairnsdale_relative_humidity
    entity_pop: sensor.bom_bairnsdale_chance_of_rain_0
    entity_pop_1: sensor.bom_bairnsdale_chance_of_rain_1
    entity_pop_2: sensor.bom_bairnsdale_chance_of_rain_2
    entity_pop_3: sensor.bom_bairnsdale_chance_of_rain_3
    entity_pop_4: sensor.bom_bairnsdale_chance_of_rain_4
    entity_pop_5: sensor.bom_bairnsdale_chance_of_rain_5
    entity_pop_intensity: sensor.bom_bairnsdale_rain_today
    entity_summary_1: sensor.bom_bairnsdale_summary_1
    entity_summary_2: sensor.bom_bairnsdale_summary_2
    entity_summary_3: sensor.bom_bairnsdale_summary_3
    entity_summary_4: sensor.bom_bairnsdale_summary_4
    entity_summary_5: sensor.bom_bairnsdale_summary_5
    entity_temperature: sensor.bom_bairnsdale_air_temp_c
    entity_wind_bearing: sensor.bom_bairnsdale_wind_direction
    entity_wind_speed: sensor.bom_bairnsdale_wind_speed_kmh
    title: BOM Weather
    type: 'custom:bom-weather-card'
type: vertical-stack
```
