### ISSUE TITLE
The card is not displayed after update to 0.86a

### ISSUE THREAD

**Issue by bieniu** [DavidFW1960/bom-weather-card#44]
After updating to 0.86a (HA 2020.12.1), the card is not displayed and there are errors in the browser console:
```
Uncaught (in promise) TypeError: Cannot read property 'state' of undefined
    at HTMLElement.slotValue (bom-weather-card.js:124)
    at HTMLElement.getSlot (bom-weather-card.js:100)
    at HTMLElement.render (bom-weather-card.js:57)
    at HTMLElement.update (app.e45b0549.js:10297)
    at HTMLElement.performUpdate (app.e45b0549.js:10297)
    at HTMLElement._enqueueUpdate (app.e45b0549.js:10297)
```
Card configuration:
```yaml
          - type: custom:bom-weather-card
            entity_sun: sun.sun
            entity_daily_summary: sensor.dark_sky_daily_summary
            entity_current_conditions: sensor.dark_sky_icon
            entity_humidity: sensor.humidity_outdoor
            entity_pressure: sensor.pressure_outdoor
            entity_temperature: sensor.temperature_outdoor
            entity_apparent_temp: sensor.dom_realfeel_temperature
            entity_wind_bearing: sensor.dark_sky_wind_bearing
            entity_wind_speed: sensor.dark_sky_wind_speed
            entity_pop: sensor.dark_sky_precip_probability
            entity_pop_intensity: sensor.dom_precipitation
            entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1d
            entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2d
            entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3d
            entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4d
            entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5d
            entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature_1d
            entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_2d
            entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_3d
            entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_4d
            entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_5d
            entity_forecast_icon_1: sensor.dark_sky_icon_1d
            entity_forecast_icon_2: sensor.dark_sky_icon_2d
            entity_forecast_icon_3: sensor.dark_sky_icon_3d
            entity_forecast_icon_4: sensor.dark_sky_icon_4d
            entity_forecast_icon_5: sensor.dark_sky_icon_5d
            entity_summary_1: sensor.dark_sky_summary_1d
            entity_summary_2: sensor.dark_sky_summary_2d
            entity_summary_3: sensor.dark_sky_summary_3d
            entity_summary_4: sensor.dark_sky_summary_4d
            entity_summary_5: sensor.dark_sky_summary_5d
            entity_pop_1: sensor.dark_sky_precip_probability_1d
            entity_pop_2: sensor.dark_sky_precip_probability_2d
            entity_pop_3: sensor.dark_sky_precip_probability_3d
            entity_pop_4: sensor.dark_sky_precip_probability_4d
            entity_pop_5: sensor.dark_sky_precip_probability_5d
            current_data_top_margin: 7em
            time_format: 24
            locale: pl
            tooltips: true
            tooltip_width: 100
            tooltip_bg_color: "#FAFAFA"
            tooltip_fg_color: "#212121"
            tooltip_border_color: "#D9D9D9"
            tooltip_left_offset: -14
            slot_l1: "wind"
            slot_l2: "pop"
            slot_l3: "sun_following"
            slot_l4: "remove"
            slot_l5: "remove"
            slot_r1: "humidity"
            slot_r2: "pressure"
            slot_r3: "sun_next"
            slot_r4: "remove"
            slot_r5: "remove"
            old_icon: "true"
            show_decimals: true
```
