### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by beasthouse-au** [DavidFW1960/bom-weather-card#49]
Since updating Home Assistant to 2021.4, I have received the following Invalid config notification. I believe this relates to the bom-weather-card and am hoping that you will be able to provide some help in fixing. I cannot decipher the code. It does mention Script in the notification, and the code it provides in the Log suggests line 14 of my configuration.yaml file which is my scripts.yaml. I have gone through Scripts and there is no script pertaining to the BOM-Weather-Card...

![Capture](https://user-images.githubusercontent.com/78465928/114118458-331bc200-992c-11eb-9cfe-117f28692ac3.JPG)

Logger: homeassistant.config
Source: config.py:437
First occurred: 10:41:38 (1 occurrences)
Last logged: 10:41:38

Invalid config for [script]: expected a dictionary. Got OrderedDict([('homeassistant', OrderedDict([('name', 'Home'), ('latitude', -xx.xxxxxx), ('longitude', xxx.xxxxx), ('elevation', 24), ('unit_system', 'metric'), ('time_zone', 'Australia/Sydney'), ('internal_url', 'http://homeassistant.local:8123'), ('packages', OrderedDict([('weather', OrderedDict([('sensor', [OrderedDict([('platform', 'template'), ('sensors', OrderedDict([('bom_current_text', OrderedDict([('value_template', "{% set val = states('sensor.zetland_short_text_0').split('.')[0] %} .... (See /config/configuration.yaml, line 14).

And my config yaml for reference.

```yaml
homeassistant: !include homeassistant.yaml

logger:
  default: info

default_config:
mobile_app:
discovery:
frontend: !include frontend.yaml
tts: !include tts.yaml

cloud: !include cloud.yaml
group: !include groups.yaml

script: !include scripts.yaml
automation: !include automations.yaml
scene: !include scenes.yaml

device_tracker: !include device_tracker.yaml
input_select: !include input_select.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
zone: !include zones.yaml
proximity: !include proximity.yaml

light: !include light.yaml
switch: !include switch.yaml
climate: !include climate.yaml

spotify: !include spotify.yaml
#spotcast: !include spotcast.yaml
```
