### ISSUE TITLE
Today's Low NaN °C

### ISSUE THREAD

**Issue by quadhammer** [DavidFW1960/bom-weather-card#52]
I've stated getting this just recently:
Today's Low NaN °C

on my card using:
entity_daytime_low: sensor.bom_today_min

This is the one I use, the other is commented out.  Not sure on the differences between the two, but both seem to give me the error.
```
      bom_today_min:
        value_template: >
          {%- if states('sensor.suburbname_temp_min_0') == 'n/a' -%} 
            {{ state_attr('sensor.today_temp_bom', 'min_value') }}
          {% else %}
            {{ states('sensor.suburbname_temp_min_0') }}
          {% endif %}
```

bom_today_min is "Unknown"

sensor.suburbname_temp_min_0 is "Unknown"

Is this just a problem with the BOM data?
Thanks

**Comment by DavidFW1960** [comment]
Taking a wild stab at it.... you are using the custom_component Average and updated it over the weekend without reading the breaking changes?

**Comment by quadhammer** [comment]
It seems to have fixed itself without any intervention from me.  I did search for averages under configuration/entities as you suggested in the average thread, but I couldn't find anything with _2 on it, just "sensor.today_temp_bom"

I've switched to the statistic one instead, just in case.

Can I ask what the difference is between the one listed above, and this one here:

```
#      bom_today_min:
#        value_template: >
#          {{ state_attr('sensor.today_temp_bom', 'min_value') }}
```

Thank you.

**Comment by DavidFW1960** [comment]
The first one listed looks to see if the forecast sensor is available or not (state n/a) and if unavailable it falls back to the average one. The forecast one (min) is normally reached at around 4am and BOM used to make it unavailable around them but with the new API seems to be at night some time. So I substituted to just use the actual average to extract the real minimum as the forecast minimum doesn't really mean anything after 4am.

I'd go back to average instead of statistics as it is the true minimum for today if you use that. If you get an error then check the states of sensor.today_temp_bom too.. there may be an _2 for that one. Also check bom_today_min and max.

When you updated the average integration it would have created _2 sensors and all the old ones without the _2 will be unavailable which is the error you were first seeing. Best way to fix is to delete all the original ones without the _2 in config>entities (search for average)  Also search for sensor.today_temp_bom and (without the _2) and delete that as well then restart HA and all the _2 ones will have the original names again...

**Comment by quadhammer** [comment]
I deleted the average entity, and re-enabled the average sensor in the weather.yaml but surprisingly it's not showing up in my entities anymore, and I made sure any hidden/disabled entities were showing.

Well, sensor.today_temp_bom shows up, but the integration is "sensor", rather than "average".

I can't delete it though, because it has been configured in .yaml.  It gives this error:

```
This entity ("sensor.today_temp_bom") does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail. 
```

bom_today_min and  bom_today_max didn't have any _2.

Thanks for your your help, yet again. :)

**Comment by DavidFW1960** [comment]
The new average is just showing as a sensor now, not in the average integration anymore
![image](https://user-images.githubusercontent.com/36390762/118091047-af169780-b40d-11eb-931f-04aa360b90ec.png)
The min and max won't have any _2 because they are template sensors never part of the average integration.. They are extracted as attributes of sensor.today_temp_bom which is created by average (or statistics)

**Comment by quadhammer** [comment]
I'm still getting this off and on. You can see my BOM sensor is quite often going to Unknown.  When it does, then I get the NaN error
https://imgur.com/a/L6b0QhR

**Comment by DavidFW1960** [comment]
What does today.temp.bom show?
What are your template sensors?
What states do the entities used for the templates show?
This is specific to your config.

**Comment by quadhammer** [comment]
```

**Comment by quadhammer** [comment]
today_temp_bom is fine.  No Unknowns for 24 hours

This one works:
```
      bom_today_min:
        value_template: >
          {{ state_attr('sensor.today_temp_bom', 'min_value') }}
```

This one doesn't, reliably anyway:
```
      bom_today_min:
        value_template: >
          {%- if states('sensor.suburbname_temp_min_0') == 'n/a' -%} 
            {{ state_attr('sensor.today_temp_bom', 'min_value') }}
          {% else %}
            {{ states('sensor.suburbname_temp_min_0') }}
          {% endif %}
```

          {%- if states('sensor.suburbname_temp_min_0') == 'n/a' -%} 

Should the 'n/a' be 'Unknown'?

**Comment by DavidFW1960** [comment]
I assume you are using the real suburbname? What does sensor.suburbname_temp_min_0 show for it's states? Pretty sure BOM shows the state as n/a when a forecast is removed/unavailable.

**Comment by DavidFW1960** [comment]
If you are still having issues and you are using weather.yaml package, please email me the yaml file and your location lat/long and I will run this up in my dev VM and work out where the error is. I'm closing this issue though because it's not a problem with the card - it seems to be a template issue.

**Comment by quadhammer** [comment]
> I assume you are using the real suburbname?

Yes



> What does sensor.suburbname_temp_min_0 show for it's states?

You can see here:
https://i.imgur.com/K4Xl0Rd.png

I posted 2 shots above.  It says 'Unknown'.

**Comment by quadhammer** [comment]
> please email me the yaml file and your location lat/long and I will run this up in my dev VM and work out where the error is. I'm closing this issue though because it's not a problem with the card - it seems to be a template issue.

Yes, I think it's a template issue too.  How can I find your mail, or DM on here, please?

**Comment by DavidFW1960** [comment]
Sorry I meant to put my email here for you. Please send to david@wilfam.net - include yaml file and your location so I can easily create the location sensors. Thanks.

**Comment by DavidFW1960** [comment]
Sorry for the delay.... I'll look at your sent data tomorrow.. just need flat out

**Comment by quadhammer** [comment]
No rush at all, mate.  Thanks for looking.

**Comment by DavidFW1960** [comment]
All looks ok so far
![image](https://user-images.githubusercontent.com/36390762/119594510-44a72380-be1f-11eb-9b3c-e8c8a3903167.png)
I'll keep the VM up for a day or so and monitor the history.
The templates look ok.

**Comment by DavidFW1960** [comment]
Still looks ok to me and I see no gaps in the history.
I did notice one thing from your config
```
      bom_today_max:
        value_template: >
          {%- if states('sensor.clayfield_temp_max_0') == 'n/a' -%} 
            {{ state_attr('sensor.today_temp_bom', 'max_value') }}
          {% else %}
            {{ states('sensor.clayfield_temp_max_0') }}
          {% endif %}


# ONLY USE ONE bom_today_min below:
      bom_today_min:
        value_template: >
          {{ state_attr('sensor.today_temp_bom', 'min_value') }}

#      bom_today_min:
#        value_template: >
#          {%- if states('sensor.clayfield_temp_min_0') == 'n/a' -%} 
#            {{ state_attr('sensor.today_temp_bom', 'min_value') }}
#          {% else %}
#            {{ states('sensor.clayfield_temp_min_0') }}
#          {% endif %}

# IMPORTANT NOTE IF YOU USE average, you must comment out the below statistics sensor. Both cannot exist
# https://github.com/Limych/ha-average
  - platform: average
    name: today_temp_bom
    entities:
      - sensor.brisbane_temp
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
```

For the max you are using the _0 temp forecast if available but for the min you are always using the average calc value... which is totally fine as long as that's what you want. I have just been using the actual min/max for today and ignoring the forecast values completely but that's just my preference. I had been toying with the idea of adding actual mn/max and forecast min/max to the card before... It's just a personal preference and your way here is fine...
