### ISSUE TITLE
Cannot get your card to show

### ISSUE THREAD

**Issue by remirr** [DavidFW1960/bom-weather-card#56]
Hi there,

First of all, great write up and very detailed - love it for people like me who are just learning this. I followed every step, got BOM installed, set my location, it created the sensors. 

I copied your code, change the sensor names to mine but unfortunately it isnt working... any ideas? I would like to get the card you have in your example. 

Thank you!

![Screen Shot 2021-06-19 at 16 47 28](https://user-images.githubusercontent.com/2309583/122655141-457d5d80-d11e-11eb-9e86-53e108714fa8.png)

![bom-weather](https://user-images.githubusercontent.com/2309583/122655143-49a97b00-d11e-11eb-936d-c2a83737c633.png)

**Comment by DavidFW1960** [comment]
OK so looks to me like you have sending sensors to the card that don't exist. Typically the forecast sensors will have a different prefix to the observations and also some of the entities require the template sensors. So the best thing to check is to open dev-tools states page and check that all the sensors exist and are available. The only reason the card won't show is because some sensors are missing.

**Comment by DavidFW1960** [comment]
So no response....
If you are still having problems, show me your full lovelace config (post the code not a screenshot) as well as any yaml templates you are using and send your lat/long to david@wilfam.net so I can set up the same BOM sensors as you and see what the issue is. Otherwise I'm closing this now.

**Comment by remirr** [comment]
Thank you for your response @DavidFW1960 and sorry for the late response, I have been super busy with work this week and have not had a change to come back to this until today. 

So I took a look and indeed the sensors are different to what I had posted, I had simply copied your YAML and replaced your location with mine in the hopes that it worked - alas it did not. 

So I have noticed that the sensors change between sensor.adelaide_west_terrace_ngayirdpira and sensor.stepeters.xxx

Is the code below essentially the code required to create the card above? and is the temp_max_1, 2, 3 etc the different days?

Thanks so much!

type: custom:bom-weather-card
title: BOM Weather
entity_current_conditions: sensor.adelaide_west_terrace_ngayirdapira_icon_descriptor_0
entity_temperature: sensor.adelaide_west_terrace_ngayirdapira_temp
entity_forecast_high_temp_1: sensor.adelaide_west_terrace_ngayirdapira_temp_max_1
entity_forecast_high_temp_2: sensor.adelaide_west_terrace_ngayirdapira_temp_max_2
entity_forecast_high_temp_3: sensor.adelaide_west_terrace_ngayirdapira_temp_max_3
entity_forecast_high_temp_4: sensor.adelaide_west_terrace_ngayirdapirag_temp_max_4
entity_forecast_high_temp_5: sensor.adelaide_west_terrace_ngayirdapira_temp_max_5
entity_forecast_icon_1: sensor.adelaide_west_terrace_ngayirdapira_icon_descriptor_1
entity_forecast_icon_2: sensor.adelaide_west_terrace_ngayirdapira_icon_descriptor_2
entity_forecast_icon_3: sensor.adelaide_west_terrace_ngayirdapira_icon_descriptor_3
entity_forecast_icon_4: sensor.adelaide_west_terrace_ngayirdapira_icon_descriptor_4
entity_forecast_icon_5: sensor.adelaide_west_terrace_ngayirdapira_icon_descriptor_5
entity_forecast_low_temp_1: sensor.adelaide_west_terrace_ngayirdapira_temp_min_1
entity_forecast_low_temp_2: sensor.adelaide_west_terrace_ngayirdapira_temp_min_2
entity_forecast_low_temp_3: sensor.adelaide_west_terrace_ngayirdapira_temp_min_3
entity_forecast_low_temp_4: sensor.adelaide_west_terrace_ngayirdapira_temp_min_4
entity_forecast_low_temp_5: sensor.adelaide_west_terrace_ngayirdapira_temp_min_5
entity_summary_1: sensor.adelaide_west_terrace_ngayirdapira_short_text_1
entity_summary_2: sensor.adelaide_west_terrace_ngayirdapira_short_text_2
entity_summary_3: sensor.adelaide_west_terrace_ngayirdapira_short_text_3
entity_summary_4: sensor.adelaide_west_terrace_ngayirdapira_short_text_4
entity_summary_5: sensor.adelaide_west_terrace_ngayirdapira_short_text_5
entity_sun: sun.sun

**Comment by DavidFW1960** [comment]
Please email your lat/long so I can create your sensors to test the yaml and find the issue.

**Comment by remirr** [comment]
Thanks so much @DavidFW1960, I have sent through an email - really appreciate it :)

**Comment by DavidFW1960** [comment]
OK So I added your location and using the default names, I see:
sensor.adelaide_west_terrace_ngayirdapira_* for the Observation sensors and I see sensor.st_peters_* for the forecast sensors
SO..
```
type: custom:bom-weather-card
title: BOM Weather
entity_temperature: sensor.adelaide_west_terrace_ngayirdapira_temp
entity_current_conditions: sensor.st_peters_icon_descriptor_0
entity_forecast_high_temp_1: sensor.st_peters_temp_max_1
entity_forecast_high_temp_2: sensor.st_peters_temp_max_2
entity_forecast_high_temp_3: sensor.st_peters_temp_max_3
entity_forecast_high_temp_4: sensor.st_peters_temp_max_4
entity_forecast_high_temp_5: sensor.st_peters_temp_max_5
entity_forecast_icon_1: sensor.st_peters_icon_descriptor_1
entity_forecast_icon_2: sensor.st_peters_icon_descriptor_2
entity_forecast_icon_3: sensor.st_peters_icon_descriptor_3
entity_forecast_icon_4: sensor.st_peters_icon_descriptor_4
entity_forecast_icon_5: sensor.st_peters_icon_descriptor_5
entity_forecast_low_temp_1: sensor.st_peters_temp_min_1
entity_forecast_low_temp_2: sensor.st_peters_temp_min_2
entity_forecast_low_temp_3: sensor.st_peters_temp_min_3
entity_forecast_low_temp_4: sensor.st_peters_temp_min_4
entity_forecast_low_temp_5: sensor.st_peters_temp_min_5
entity_summary_1: sensor.st_peters_short_text_1
entity_summary_2: sensor.st_peters_short_text_2
entity_summary_3: sensor.st_peters_short_text_3
entity_summary_4: sensor.st_peters_short_text_4
entity_summary_5: sensor.st_peters_short_text_5
entity_sun: sun.sun
```
Works thus:
![image](https://user-images.githubusercontent.com/36390762/124061836-f666ef00-da72-11eb-9e71-cea35a507f29.png)

Which is a start but you will need to add some additional sensors to create my example and also some template sensors to get the current text etc...

So see how you go with that..

**Comment by remirr** [comment]
Thank you so much, I will give that a shot How did you get the text in the middle and at the bottom?

**Comment by DavidFW1960** [comment]
Dude read the docs and the use the example templates and full lovelace configuration not just the minimal one.

**Comment by jkelly73** [comment]
Hi David,
I am a noob at HA but have tried to follow your install docs to the letter, although I suspect Ive done something wrong somewhere... When I add the Lovelace card in HA, the card is blank.

I installed through HACS and the line "/hacsfiles/bom-weather-card/bom-weather-card.js" was added as a "JavaScript Module" to the resources section.  Now I can add the Lovelace card to the dashboard.  When I goto add a card, I am presented with this:
<img width="327" alt="Screen Shot 2021-08-18 at 12 32 26" src="https://user-images.githubusercontent.com/85336126/129827328-2fda3ca2-3b1a-4966-8421-f92811cc3658.png">
Is this what it it should look like, or should it resemble this?:
![card-picker](https://user-images.githubusercontent.com/85336126/129827449-2869359e-5250-46c6-80ef-448f5c6ced31.png)

I have installed the BOM plug in and have those sensors working in a standard entity card, but cannot get your card to populate.  When I added the card described above, I edited the yaml as per below:
```
`type: custom:bom-weather-card
title: BOM Weather
entity_current_conditions: sensor.murrays_run_icon_descriptor_0
entity_temperature: sensor.gosford_temp
entity_forecast_high_temp_1: sensor.murrays_run_temp_max_1
entity_forecast_high_temp_2: sensor.murrays_run_temp_max_2
entity_forecast_high_temp_3: sensor.murrays_run_temp_max_3
entity_forecast_high_temp_4: sensor.murrays_run_temp_max_4
entity_forecast_high_temp_5: sensor.murrays_run_temp_max_5
entity_forecast_icon_1: sensor.murrays_run_icon_descriptor_1
entity_forecast_icon_2: sensor.murrays_run_icon_descriptor_2
entity_forecast_icon_3: sensor.murrays_run_icon_descriptor_3
entity_forecast_icon_4: sensor.murrays_run_icon_descriptor_4
entity_forecast_icon_5: sensor.murrays_run_icon_descriptor_5
entity_forecast_low_temp_1: sensor.murrays_run_temp_min_1
entity_forecast_low_temp_2: sensor.murrays_run_temp_min_2
entity_forecast_low_temp_3: sensor.murrays_run_temp_min_3
entity_forecast_low_temp_4: sensor.murrays_run_temp_min_4
entity_forecast_low_temp_5: sensor.murrays_run_temp_min_5
entity_summary_1: sensor.murrays_run_short_text_1
entity_summary_2: sensor.murrays_run_short_text_2
entity_summary_3: sensor.murrays_run_short_text_3
entity_summary_4: sensor.murrays_run_short_text_4
entity_summary_5: sensor.murrays_run_short_text_5
locale: en
sunset: true
static_icons: false
old_icon: hybrid
tooltip_bg_color: rgb( 75,155,239)
tooltip_border_color: rgb(255,161,0)
tooltip_border_width: 1
tooltip_caret_size: 5
tooltip_fg_color: '#fff'
tooltip_left_offset: -12
tooltip_width: 110
tooltips: true
old_daily_format: false
time_format: 12
show_beaufort: false
refresh_interval: 60
show_separator: false
temp_top_margin: 0px
temp_font_weight: 300
temp_font_size: 4em
temp_right_pos: 0.85em
temp_uom_top_margin: '-12px'
temp_uom_right_margin: 4px
apparent_top_margin: 45px
apparent_right_pos: 1em
apparent_right_margin: 1em
current_text_top_margin: 4.5em
current_text_left_pos: 0px
current_text_font_size: 1.5em
current_text_alignment: center
current_text_width: 100%
current_data_top_margin: 10em
large_icon_top_margin: '-3.2em'
large_icon_left_position: 0px
separator_top_margin: 6em
summary_top_padding: 2em
summary_font_size: 0.8em
slot_l1: daytime_high
slot_l2: daytime_low
slot_l3: wind
slot_l4: pressure
slot_l5: sun_next
slot_r1: pop
slot_r2: humidity
slot_r3: uv_summary
slot_r4: fire_summary
slot_r5: sun_following
`
```
I have also revised your weather.yaml to revise references from kariong and gosford to mangrove_mountain and murrays_run and downloaded the icons and put them in the folder structure you mention in the install doc...

Looking for a few words of wisdom to help me find my way!

Thanks
Jon

**Comment by DavidFW1960** [comment]
It should look like:
![image](https://user-images.githubusercontent.com/36390762/129837056-ab6f65f8-eb66-485f-8db7-0a11669d55f9.png)
ie the second one (probably depends on the theme you are using)
Click on it:
you should see something like this
![image](https://user-images.githubusercontent.com/36390762/129837164-1095f88d-3dbe-43bd-b699-6db3b1b4e14e.png)
Where you put the config.
Your resourse should look like this:
![image](https://user-images.githubusercontent.com/36390762/129837338-46f95502-fca7-4aed-88be-718646203cff.png)
with the hacs tag at the end......

**Comment by jkelly73** [comment]
Thanks David.
I suspect you might be onto something re the theme in terms of the black on white in your screenshots and white on black in mine.  However, I dont have the hacs tag in the resources.  Is that a unique ID at the end, or can I use the number in the screenshot above?  If its unique, how do I establish what it should be?

Thanks
Jon

**Comment by DavidFW1960** [comment]
As long as you are using the latest HACS it should include the HACS tag itself. The tag needs to be put there by HACS as it uses that to ensure HACS installed it and you will get an error if it didn't and HACS is loaded. It uses that tag to prevent the !@#$%^&* annoying chrome caching when you update the card. HACS should store the URL with the tag itself.

**Comment by jkelly73** [comment]
Thanks David.  Finally got it working by going over your instructions again (and again) and double checking that all my entities that you identified as the minimum required for it to work were in-fact valid.  I can confirm that it only takes one miss-spelt entity to stop the thing working entirely!

Only one smaller problem now and I suspect it might be entity related and that is that my "Today's High" and "Today's Low" always show 'NaN'
<img width="547" alt="Screen Shot 2021-08-24 at 16 51 13" src="https://user-images.githubusercontent.com/85336126/130570265-0cd19ef0-eb13-4085-8da1-7b78eaa95fc3.png">

Im pretty sure that I read something about this when I first started reading about your card, but of course I cant find it now!  Any pointers to this problem would be grately appreciated.

Thx
Jon

**Comment by DavidFW1960** [comment]
Typically you need template sensors and either statistics or a custom-component (average) to fill in the high/low when BOM stops publishing values (typically in the afternoon). There are examples in the weather.yaml package. Make sure the entity you are pushing to the card for min/max has a real value...

**Comment by jkelly73** [comment]
Thanks David.  Ive looked at this a bit more in the card and also weather yaml.
Considering only the Max temps at the moment as the Min looks to work in exactly the same way...

My High entity is "sensor.murrays_run_temp_max_0".  This has a value and shows the correct data if I put it into a standard entity card.  This is also correctly entered into weather.yaml.  Still within weather.yaml, associated with the High value there is an entity sensor.bom_today_max.  This returns a value of 'Unknown'.  I found further down in weather.yaml; where this value is defined.  It appears to come via sensor.today_temp_bom and I do not have this entity in my HA.  This is where my trail goes dead.  I am not sure what to do with this now.

An alternative appears to be discussed / suggested in weather.yaml and requires the above routines to be ## out and the alternative un-##.  When I do this and modify the appropriate line entry in the card (entity_daytime_high: sensor.murrays_run_temp_max_0), after a restart I can see the correct High.

This alternative appears to still try to get a value from sensor.today_temp_bom snd in the event it fails, fall back to sensor.murrays_run_temp_max_0.

Am I correct in thinking that the only difference is that if / when BOM stops publishing the High, with the first / default option, the High will not goto NaN because its using an internal value, whereas with the second option, if/when stops publishing the High reverts to Nan (until it gets re-published tomorrow)?

Thx
J

**Comment by DavidFW1960** [comment]
You can parse that through to the card as the max if you want BUT BOM will publish that as N/A at some poing through the day. It used to be at ~ 4PM but now seems to be ~ 10PM. The Min used to be N/A at ~4AM and now does it during the afternoon.

The statistics seensor or custom average component will use the current temperature for the past day to calculate the average value (which is useless) but it also gets the minimum and maximum temperature from that and a template sensor in the yaml file then populates sensor.bom_today_max and sensor.bom_today_min. If you don't have sensor.today_temp_bom you have not created the statistics sensor OT the average component correctly. You can ONLY use one of those components - statistics or average and you comment the other one out (with the ## or delete the lines)

> This alternative appears to still try to get a value from sensor.today_temp_bom snd in the event it fails, fall back to sensor.murrays_run_temp_max_0.

You can do that and I used to do it previously (and still do for the minimal card) but I find it more valuable if it returns the actual values... but you can do whatever makes sense to you.

> Am I correct in thinking that the only difference is that if / when BOM stops publishing the High, with the first / default option, the High will not goto NaN because its using an internal value, whereas with the second option, if/when stops publishing the High reverts to Nan (until it gets re-published tomorrow)?

Yep.

**Comment by MasterCATZ** [comment]
Still getting blanks using the sample template with no edits 

what sensor in the template might actually be missing ?

**Comment by DavidFW1960** [comment]
Have you checked all the sensors in the card exist? Check one by one in dev-tools. Its likely to be pressure. BOM pretty much doesn't supply pressure so unless you have some other source as I do that can cause a problem.

**Comment by MasterCATZ** [comment]
I do not even have pressure sensor in the config file and its still trying to run it ? 
![Screenshot from 2022-04-29 16-56-30](https://user-images.githubusercontent.com/1857824/165898081-5c2d5265-0b5b-4ff7-ae3a-92466c55fdae.png)

**Comment by MasterCATZ** [comment]
I have not even been able to get that far , nothing related to this displays 

or is that some option to do with https://github.com/bremor/bureau_of_meteorology

**Comment by DavidFW1960** [comment]
Pressure is slot L4 slot by default unless you override it manually. The slot defaults are shown in the docs. Normally if you dont define a slot it will automatically be blank but we screwed up with the new method of UOM for pressure that it blanked the card if there was no pressure entity. 
We fixed this today with 1.02 so you can pull the master or set slot L4: empty should fix it

**Comment by DavidFW1960** [comment]
We are looking at a release next week that will do error checking on the card and tell you what entity is causing this problem

**Comment by MasterCATZ** [comment]
![Screenshot from 2022-04-29 16-56-30](https://user-images.githubusercontent.com/1857824/165903719-ae597cd5-3d57-4179-9a9b-4cf0c0319178.png)

it hates me 

can you verify where the "weather.yaml" "illuminance.yaml" files should live ? 

I have been using "lovelace.yaml" 
as the data when I go edit card as by default its only contains 
"type: custom:bom-weather-card" 

installed with HACS

I downloaded the icons and they are in /config/www/community/icons

/config/www/community/bom-weather-card

contains just bom-weather-card.js

Home Assistant 2022.4.7
Host Operating System | Home Assistant OS 7.6
Update Channel | stable
Supervisor Version | supervisor-2022.04.0
Docker Version | 20.10.9

**Comment by DavidFW1960** [comment]
Yeah i didnt bump the version in js before I did the release. If you pull master it will be 1.02. 

Weather.yaml and illuminance.yaml are packages. They go in /config/packages. Totally seperate to lovelace. You can look up packages in ha docs. 

Are the icons in the right place re my readme file? I can't remember and I'm on my phone at the moment

**Comment by DavidFW1960** [comment]
If you edit the card in the gui it should list all the entities and configuration for the card not just the type. Might be caching? I can give this more attention tomorrow when i am at my computer. I do have some lawn mowing duties in the morning though. You should be able to paste the contents of lovelace.yaml into the gui card editor

**Comment by MasterCATZ** [comment]
their is no GUI and I have used multiple browsers so not a caching issue 




the last version from today has this error 
![Screenshot from 2022-04-29 18-42-37](https://user-images.githubusercontent.com/1857824/165912408-4375762a-007e-4b93-bcc2-a0b0d34c4e49.png)



```
get currentApparent() {
    var places = this.config.show_decimals ? 1 : 0;
    return this.config.entity_apparent_temp ? Number(this._hass.states[this.config.entity_apparent_temp].state).toLocaleString(undefined, {minimumFractionDigits: places, maximumFractionDigits: places}) : 0;
  }
```


here a video

https://drive.google.com/file/d/1M89GPAbDRANOJppYbd88AWXiN7V5thnW/view?usp=sharing

**Comment by DavidFW1960** [comment]
Have you taken control of Lovelace? If you have then you paste the yaml here
![image](https://user-images.githubusercontent.com/36390762/165920381-e7f662a1-ed11-482d-a692-14ea86d82dde.png)
Otherwise the lovelace file you are using (but the indenting in my example won't be right probably

**Comment by MasterCATZ** [comment]
```
views:
  - title: Home
    cards:
      - type: custom:bom-weather-card
        title: BOM Weather
        entity_current_conditions: sensor.kariong_icon_descriptor_0
        entity_temperature: sensor.gosford_temp
        entity_forecast_high_temp_1: sensor.kariong_temp_max_1
        entity_forecast_high_temp_2: sensor.kariong_temp_max_2
        entity_forecast_high_temp_3: sensor.kariong_temp_max_3
        entity_forecast_high_temp_4: sensor.kariong_temp_max_4
        entity_forecast_high_temp_5: sensor.kariong_temp_max_5
        entity_forecast_icon_1: sensor.kariong_icon_descriptor_1
        entity_forecast_icon_2: sensor.kariong_icon_descriptor_2
        entity_forecast_icon_3: sensor.kariong_icon_descriptor_3
        entity_forecast_icon_4: sensor.kariong_icon_descriptor_4
        entity_forecast_icon_5: sensor.kariong_icon_descriptor_5
        entity_forecast_low_temp_1: sensor.kariong_temp_min_1
        entity_forecast_low_temp_2: sensor.kariong_temp_min_2
        entity_forecast_low_temp_3: sensor.kariong_temp_min_3
        entity_forecast_low_temp_4: sensor.kariong_temp_min_4
        entity_forecast_low_temp_5: sensor.kariong_temp_min_5
        entity_summary_1: sensor.kariong_short_text_1
        entity_summary_2: sensor.kariong_short_text_2
        entity_summary_3: sensor.kariong_short_text_3
        entity_summary_4: sensor.kariong_short_text_4
        entity_summary_5: sensor.kariong_short_text_5
        entity_sun: sun.sun
        entity_daytime_high: sensor.bom_today_max
        entity_daytime_low: sensor.bom_today_min
        entity_wind_bearing: sensor.gosford_wind_direction
        entity_wind_speed: sensor.gosford_wind_speed_kilometre
        entity_wind_gust: sensor.gosford_gust_speed_kilometre
        entity_humidity: sensor.gosford_humidity
        entity_apparent_temp: sensor.gosford_temp_feels_like
        entity_daily_summary: sensor.kariong_extended_text_0
        entity_pop: sensor.kariong_rain_chance_0
        entity_pop_intensity: sensor.gosford_rain_since_9am
        entity_possible_today: sensor.kariong_rain_amount_range_0
        entity_pos_1: sensor.kariong_rain_amount_range_1
        entity_pos_2: sensor.kariong_rain_amount_range_2
        entity_pos_3: sensor.kariong_rain_amount_range_3
        entity_pos_4: sensor.kariong_rain_amount_range_4
        entity_pos_5: sensor.kariong_rain_amount_range_5
        entity_pop_1: sensor.kariong_rain_chance_1
        entity_pop_2: sensor.kariong_rain_chance_2
        entity_pop_3: sensor.kariong_rain_chance_3
        entity_pop_4: sensor.kariong_rain_chance_4
        entity_pop_5: sensor.kariong_rain_chance_5
        entity_current_text: sensor.bom_current_text
        entity_uv_alert: sensor.bom_uv_alert
        entity_fire_danger: sensor.bom_fire_danger
        entity_uv_alert_summary: sensor.uv_cat_formatted
        entity_fire_danger_summary: sensor.kariong_fire_danger_0
        locale: en
        sunset: true
        static_icons: false
        old_icon: hybrid
        tooltip_bg_color: rgb( 75,155,239)
        tooltip_border_color: rgb(255,161,0)
        tooltip_border_width: 1
        tooltip_caret_size: 5
        tooltip_fg_color: '#fff'
        tooltip_left_offset: -12
        tooltip_width: 110
        tooltips: true
        old_daily_format: false
        time_format: 12
        show_beaufort: false
        refresh_interval: 60
        show_separator: false
        temp_top_margin: 0px
        temp_font_weight: 300
        temp_font_size: 4em
        temp_right_pos: 0.85em
        temp_uom_top_margin: '-12px'
        temp_uom_right_margin: 4px
        apparent_top_margin: 45px
        apparent_right_pos: 1em
        apparent_right_margin: 1em
        current_text_top_margin: 4.5em
        current_text_left_pos: 0px
        current_text_font_size: 1.5em
        current_text_alignment: center
        current_text_width: 100%
        current_data_top_margin: 10em
        large_icon_top_margin: '-3.2em'
        large_icon_left_position: 0px
        separator_top_margin: 6em
        summary_top_padding: 2em
        summary_font_size: 0.8em
        slot_l1: daytime_high
        slot_l2: daytime_low
        slot_l3: wind
        slot_l4: pop
        slot_l5: sun_next
        slot_r1: pop
        slot_r2: humidity
        slot_r3: uv_summary
        slot_r4: fire_summary
        slot_r5: sun_following
```

just your default with that pressure sensor changed
